"""empty message

Revision ID: 624ee34cda4e
Revises: 673f8a238dc5
Create Date: 2024-04-21 12:25:27.462302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624ee34cda4e'
down_revision = '673f8a238dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_send', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('user_receive', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('user_receive')
        batch_op.drop_column('user_send')

    # ### end Alembic commands ###
