"""empty message

Revision ID: 673f8a238dc5
Revises: ef65b150768e
Create Date: 2024-04-05 13:03:48.463081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '673f8a238dc5'
down_revision = 'ef65b150768e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.engine.reflection import Inspector
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    if 'user_listing' in inspector.get_table_names():
        op.drop_table('user_listing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_listing',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('listing_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], name='user_listing_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_listing_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id', 'listing_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
