"""empty message

Revision ID: f750d3bacb03
Revises: 673f8a238dc5
Create Date: 2024-04-23 12:27:22.061304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f750d3bacb03'
down_revision = '673f8a238dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorited_listing', schema=None) as batch_op:
        batch_op.drop_constraint('user_favorited_listing_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('user_favorited_listing_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'listing', ['listing_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_passed_listing', schema=None) as batch_op:
        batch_op.drop_constraint('user_passed_listing_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('user_passed_listing_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'listing', ['listing_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_passed_listing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_passed_listing_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('user_passed_listing_ibfk_2', 'listing', ['listing_id'], ['id'])

    with op.batch_alter_table('user_favorited_listing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_favorited_listing_ibfk_2', 'listing', ['listing_id'], ['id'])
        batch_op.create_foreign_key('user_favorited_listing_ibfk_1', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
